### ISSUE TITLE
The problem about KPC-tool

### ISSUE THREAD

**Issue by ZhaoMingYang-tju** [rickypinci/BATCH#1]
Hello!  Thanks for your amazing work. I want to know how to use the KPC-toolbox to fit the sequence of arrivals into a stochastic process (like MAP1_D0 and MAP1_D1 in your work). Can you  tell me the details about the instructions in MATLAB, please? Thank you for your answer!

**Comment by rickypinci** [comment]
Hi, to fit inter-arrival times into a Markovian Arrival Process, we used: _kpcfit_auto.m_ and _map2_fit.m_.

You may want to give a look at the KPC toolbox GitHub page (https://github.com/kpctoolboxteam/kpc-toolbox) for further information.

Best,
Riccardo

**Comment by ZhaoMingYang-tju** [comment]
> Hi, to fit inter-arrival times into a Markovian Arrival Process, we used: _kpcfit_auto.m_ and _map2_fit.m_.
> 
> You may want to give a look at the KPC toolbox GitHub page (https://github.com/kpctoolboxteam/kpc-toolbox) for further information.
> 
> Best,
> Riccardo

Thank you for your answer. I have learn kpcfit_auto.m and map2_fit.m. 
The function map_fit.m is  [MAP,ERR]=map2_fit(e1,e2,e3,g2), can you tell me what is the four parameter "e1,e2,e3,g2" ?
 I didn't find the relevant description. Thanks a lot!
